config:
  model: "densenet"
  labeled_data_path: "../data/dl"
  labeled_category: ["cats", "dogs"]
  unlabeled_data_path: "../data/du"
  batch_size: 4
  epochs: 10
  max_iteration: 2

ceal:
  k: 20
  delta_0: 0.0005
  dr: 0.0033
